Desktop version Portfolio
Itswali/Portfolio pull request #12
Opened 2022-09-29 21:03 UTC by Itswali

This includes HTML and CSS file

- I added HTML file for both mobile and desktop version of portfolio.
- I add CSS file and use media queries for desktop on same HTML file.
- I use linters to identify and remove any errors.
- I used gitignore file to filter unwanted files.

2022-09-29 23:05 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @Itswali , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly your mobile version should still look as expected. So make to fix all your work sections and the about me section. 

## One of your work section  👇️
![Screenshot from 2022-09-29 21-42-42](https://user-images.githubusercontent.com/89228743/193156541-a2854919-7efd-4984-be68-cf3279a25519.png)

## The design on Figma 👇️

![Screenshot from 2022-09-24 00-29-46](https://user-images.githubusercontent.com/89228743/193156671-fe93c197-f597-4d47-8b3e-d1c1d6ae08a6.png)

## Your about me section 👇️
![Screenshot from 2022-09-29 21-43-29](https://user-images.githubusercontent.com/89228743/193156747-8034b979-a6c1-4e72-a898-24a6d7b9713a.png)

The about me on Figma
![Screenshot from 2022-09-29 23-02-11](https://user-images.githubusercontent.com/89228743/193157079-72992b5d-dc4f-4417-8fb0-837d07aa8993.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 23:05 UTC, ridwanediallo commented on index.html
>          </div>
- [ ] I would kindly recommend making sure that your portfolio looks like the Figma template. Your portfolio should look good from the breakpoint `768` to `1440`. Your hero section is not displaying as expected. On desktop view, there is no background image and the text and the icons moved to the left. Please make sure to fix that.

## Your hero section 👇️
![Screenshot from 2022-09-29 21-35-53](https://user-images.githubusercontent.com/89228743/193151238-c98dc850-f6e9-4a67-882d-2d158be9e31e.png)

## Figma design 👇️

![Screenshot from 2022-09-29 22-18-31](https://user-images.githubusercontent.com/89228743/193153529-f49c4c88-73dd-42cd-add3-d1cd89bc1723.png)

2022-09-29 23:05 UTC, ridwanediallo commented on index.html
>                  <h2>About Myself</h2>
- [ ] Kindly make sure to fix your about me section to stick to the Figma design.

## Your design 👇️
![Screenshot from 2022-09-29 21-38-09](https://user-images.githubusercontent.com/89228743/193155951-78523d09-aeb3-406e-94ac-34d5cd1d29f0.png)

## The one on Figma 👇️
![Screenshot from 2022-09-29 22-47-51](https://user-images.githubusercontent.com/89228743/193156001-d66d6bfc-ee36-4d38-b022-8956016eca4e.png)

2022-09-30 11:49 UTC, Itswali commented
Improved files and documented properly as suggested.

2022-09-30 12:22 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @Itswali 

Nice job✔, I liked your implementation 🔥, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.

## (Changes Required) Aspects to improve: ♻️
You did great implementing  the project requirements 🔥🔥, but you still have some issues:  
[ ] kindly fix your mobile version as the previous reviewer has mentioned :
![mobile1](https://user-images.githubusercontent.com/62156607/193266093-8e97c2d7-82d5-4d7e-9bd2-37807867af88.PNG)
![mobile2](https://user-images.githubusercontent.com/62156607/193266111-ba4f7c57-0774-4773-a4b1-b7b462c92f66.PNG)



Check the comments below 👇
  
## [Optional] suggestions:

-  Nothing to mention. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-30 12:22 UTC, nedjwab commented on index.html
> +                            some of my work and experience! If you like what you see and have a project you need coded,
[ ] kindly Fix the `font-weight` of this paragraph to match the Figma design.🤓
Your design : 
![paragraph](https://user-images.githubusercontent.com/62156607/193267257-7bb4fb95-494f-4a09-b64b-8085f07fc835.PNG)

Figma design : 
![designtext](https://user-images.githubusercontent.com/62156607/193267298-01668942-35cb-4c66-95aa-c15a3dff5c9e.PNG)

2022-09-30 12:22 UTC, nedjwab commented on index.html
> +            <div class="for_texts">
[ ] kindly fix the card design to match the template. 🤓
Your cards : 
![card1](https://user-images.githubusercontent.com/62156607/193267812-0e7b2b62-6c02-4c07-9fc4-948e239a06f5.PNG)
![deskcard2](https://user-images.githubusercontent.com/62156607/193267850-7c1049c1-152b-47d0-bc4a-07407a58399c.PNG)
![descard](https://user-images.githubusercontent.com/62156607/193267887-8b7212c7-9ba8-48e1-bb15-5f0d2c023948.PNG)


The Figma design :
![designcard](https://user-images.githubusercontent.com/62156607/193267985-adf74003-c499-492d-8646-a74c3dd75bee.PNG)

2022-09-30 12:22 UTC, nedjwab commented on index.html
>                  <h2>About Myself</h2>
[ ] kindly use the same font-weight for the languages in the about me section to match the design.🤓
Your design : 
![deskicons](https://user-images.githubusercontent.com/62156607/193268304-f002ce5b-7bfb-4be9-aaa6-42b0d39e158f.PNG)

Figma design : 
![designicons](https://user-images.githubusercontent.com/62156607/193268340-3b85e7b6-b40f-475d-be07-d0b6e8453438.PNG)

2022-09-30 13:30 UTC, Itswali commented
fix the desktop version as suggested.    Last review<3

2022-09-30 14:18 UTC, Alfredbis29 requested changes
Hi @Itswali ,
 
 Great work on making the changes requested by a previous reviewer clap You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
 
# STATUS: REQUEST CHANGES 
 ![soclose](https://user-images.githubusercontent.com/97100091/193093332-3330e339-cb38-418d-a4a1-3344f3813ea9.gif)

 ## Highlights
 * [x]  All linters are green
 * [x]  Descriptive PR `summary`
 * [x]  The project is documented in a professional way
 
 ## Required Changes 
 _Check the comments under the review._
 
 ## Optional suggestions
 * [x]  You may also consider adjusting your `typo` (`font-size`) to match the ones provided in Figma
 
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 14:18 UTC, Alfredbis29 commented on index.html
> +            <div class="for_texts">
- [ ] I can see that you made some changes but your design still need to be  improved as required in the previous review :upside_down_face: 
This is how your cards still looking like 
![frappesection](https://user-images.githubusercontent.com/88894525/193287997-90ada680-8d7e-4b04-9b2d-1d6cfdffa327.png)

Figma Design 
![designcard](https://user-images.githubusercontent.com/62156607/193267985-adf74003-c499-492d-8646-a74c3dd75bee.PNG)

2022-09-30 14:18 UTC, Alfredbis29 commented on index.html
>                  <h2>About Myself</h2>
- [ ] Great job so far but there still something to work on for your project to match the figma Design as required in the previous review :upside_down_face: , I noticed that after making changes your languages image are not displaying , you should fix the path of these icons and make sure that your following the figma design.
This is how your design looks like after changes :point_down: 

![frape3media](https://user-images.githubusercontent.com/88894525/193288869-57ba77e8-dd03-4eb3-a77d-c0b98e59c5ca.png)

2022-10-01 18:41 UTC, closed without merging